[project]
name = "opennote-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "google-generativeai>=0.8.4",
    "manim>=0.19.0",
    "python-dotenv>=1.0.1",
]
